Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 168, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from likelihood import likelihood

fig, ax = plt.subplots ()
ax.set_title ('likelihood scan', size=14)
ax.set_xlabel ('tau')
ax.set_ylabel ('likelihood')

tau = np.linspace (0.5, 5., 10000)
lik = np.arange (0., tau.size)

for i in range (tau.size) :
    lik[i] = likelihood (tau[i], exp_pdf, sample[])

plt.plot (tau, lik, 'b')  #'b' indicates is the blue color
plt.show ()
------------------


[0;36m  Cell [0;32mIn[4], line 12[0;36m[0m
[0;31m    lik[i] = likelihood (tau[i], exp_pdf, sample[])[0m
[0m                                                 ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid syntax


